#!/bin/bash


selected=$(echo "Turn Display Off
Shutdown
Reboot
Lock

Reload Hyprland
Toggle Caffeine
Switch Audio Output
Altair Storage
Connect to OnePlus Neckband
Launch Waydroid Session
Rotate Screen
Next Wallpaper" | rofi -dmenu -p "Power " -config "~/.config/rofi/config.rasi")

if [[ -z $selected ]]; then
    exit
elif [[ "$selected" == *"Shutdown"* ]]; then
    shutdown now
    # systemctl poweroff
elif [[ "$selected" == *"Reboot"* ]]; then
    reboot
    # systemctl reboot
elif [[ "$selected" == *"Logout"* ]]; then
    kill -9 -1
elif [[ "$selected" == *"Turn Display Off"* ]]; then
    hyprctl dispatch dpms off
elif [[ "$selected" == *"Toggle Caffeine"* ]]; then	
	notify-send "Deprecated."
#	sh ~/.config/hypr/scripts/caffeine.sh -t
elif [[ "$selected" == *"Reload Hyprland"* ]]; then
	hyprctl reload && notify-send "Reloaded."
elif [[ "$selected" == *"Switch Audio Output"* ]]; then
	notify-send "Deprecated."
# 	sh ~/.scripts/audio-output-switch.sh
elif [[ "$selected" == *"Altair"* ]]; then
 	sh ~/.config/hypr/scripts/sshftp.sh
elif [[ "$selected" == *"Connect to OnePlus Neckband"* ]]; then
	sh ~/.config/hypr/scripts/neckbandconnect
elif [[ "$selected" == *"Waydroid"* ]]; then
	sh ~/.config/hypr/scripts/waydroid.sh
elif [[ "$selected" == *"Rotate Screen"* ]]; then
	notify-send "Deprecated."
elif [[ "$selected" == *"Next Wallpaper"* ]]; then
  sh ~/.config/hypr/scripts/nextwal.sh
elif [[ "$selected" == *"Lock"* ]]; then
  sh ~/.config/hypr/scripts/lock.sh
fi
