#!/bin/bash


selected=$(echo "Turn Display Off
Shutdown
Reboot
Logout

Kill Window Manager
Toggle Caffeine
Switch Audio Output
Rotate Screen
Mic Mute Toggle" | rofi -dmenu -p "Power: " -config "~/.config/rofi/custom-rofi.rasi")

if [[ -z $selected ]]; then
    exit
elif [[ "$selected" == *"Shutdown"* ]]; then
    shutdown now
elif [[ "$selected" == *"Reboot"* ]]; then
    reboot
elif [[ "$selected" == *"Logout"* ]]; then
    kill -9 -1
elif [[ "$selected" == *"Turn Display Off"* ]]; then
    xset dpms force standby
elif [[ "$selected" == *"Toggle Caffeine"* ]]; then
	sh ~/.scripts/caffeine.sh -t
elif [[ "$selected" == *"Kill BSPWM"* ]]; then
	killall xinit
elif [[ "$selected" == *"Switch Audio Output"* ]]; then
	sh ~/.scripts/audio-output-switch.sh
elif [[ "$selected" == *"Rotate Screen"* ]]; then
	sh ~/.scripts/screen_rotate.sh
elif [[ "$selected" == *"Mic Mute Toggle"* ]]; then
	pactl set-source-mute @DEFAULT_SOURCE@ toggle
fi
